2021-01-09 18:15:23,579 ERROR: Exception on /edit_profile [POST] [in d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\marci\DEV\blogpractice\YeetTheMeat\app\routes.py", line 68, in edit_profile
    db.session.commit()
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
    self.transaction.commit()
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\orm\session.py", line 504, in commit
    self._prepare_impl()
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\orm\session.py", line 483, in _prepare_impl
    self.session.flush()
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2540, in flush
    self._flush(objects)
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2642, in _flush
    flush_context.execute()
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 236, in save_obj
    update,
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 995, in _emit_update_statements
    statement, multiparams
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "d:\marci\dev\blogpractice\yeetthemeat\venv\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('skateallday1', '', 4)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-09 18:24:40,208 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-09 18:26:36,617 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-09 18:47:55,254 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-09 18:48:51,681 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-09 18:49:18,848 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:06:53,274 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:06:53,896 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:06:53,896 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:09:23,598 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:10:49,263 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:12:04,100 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:15:19,911 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:15:26,781 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:17:23,987 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:18:37,413 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:18:42,814 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
2021-01-11 10:53:49,958 INFO: Microblog startup [in D:\marci\DEV\blogpractice\YeetTheMeat\app\__init__.py:45]
